#!/usr/bin/env bash

set -euo pipefail

script=$(s which "$@")

mkdir -p "$(dirname "$script")"
cat > "$script" <<EOF
#!/bin/sh

set -euo pipefail

if [ -z "$1" ]; then
    echo "Usage: `basename $0` <IP>"
else
    echo "command ran"
fi
EOF

chmod +x "$script"
s edit "$@"
